apiVersion: apps/v1
kind: Deployment
metadata:
  name: orchestrator
spec:
  template:
    spec:
      containers:
        - name: madara-orchestrator
          resources:
            limits:
              cpu: "6"
              memory: 12Gi
            requests:
              cpu: "6"
              memory: 12Gi
