// @Paradex contract schema

#[allow(non_snake_case, unused_imports, dead_code)]
pub mod account_component_layout;
#[allow(non_snake_case, unused_imports, dead_code)]
pub mod assets_future_component_layout;
#[allow(non_snake_case, unused_imports, dead_code)]
pub mod assets_manager_layout;
#[allow(non_snake_case, unused_imports, dead_code)]
pub mod assets_manager_types;
#[allow(non_snake_case, unused_imports, dead_code)]
pub mod assets_option_component_layout;
#[allow(non_snake_case, unused_imports, dead_code)]
pub mod assets_spot_component_layout;
#[allow(non_snake_case, unused_imports, dead_code)]
pub mod assets_token_component_layout;
#[allow(non_snake_case, unused_imports, dead_code)]
pub mod oracle_layout;
#[allow(non_snake_case, unused_imports, dead_code)]
pub mod oracle_types;
#[allow(non_snake_case, unused_imports, dead_code)]
pub mod paraclear_layout;
#[allow(non_snake_case, unused_imports, dead_code)]
pub mod paraclear_types;
#[allow(non_snake_case, unused_imports, dead_code)]
pub mod perpetual_asset_component_layout;
#[allow(non_snake_case, unused_imports, dead_code)]
pub mod perpetual_future_component_layout;
#[allow(non_snake_case, unused_imports, dead_code)]
pub mod perpetual_option_component_layout;
#[allow(non_snake_case, unused_imports, dead_code)]
pub mod token_component_layout;
