# yaml-language-server: $schema=https://raw.githubusercontent.com/SchemaStore/schemastore/refs/heads/master/src/schemas/json/github-action.json
name: Action - Setup Rust
description: Sets up the Rust environment with a configurable toolchain

inputs:
  rust-version:
    description: Rust version to set up
    required: true

runs:
  using: composite
  steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup Rust toolchain
      uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        toolchain: ${{ inputs.rust-version }}
        components: cargo, clippy, rustfmt

    - name: Rust version
      shell: bash
      run: rustc --version

    - name: Install wget
      shell: bash
      run: sudo apt-get update -y && sudo apt-get install wget

    - name: Setup mold
      uses: rui314/setup-mold@v1
