# yaml-language-server: $schema=https://raw.githubusercontent.com/SchemaStore/schemastore/refs/heads/master/src/schemas/json/github-action.json
name: Action - Setup Rust
description: Sets up the Rust environment with a configurable toolchain

inputs:
  rust-version:
    description: Rust version to set up
    required: true
  extra-cache:
    description: "Whether or not to enable cached dependencies"
    required: false
    default: "true"
  cache-location:
    description: "Path to cached dependencies"
    required: false
    default: "release"
  cache-key:
    description: "Cache key used to retrieve built data. Usually matches the profile of the build"
    required: false
    default: "cache"

runs:
  using: composite
  steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup Rust toolchain
      uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        toolchain: ${{ inputs.rust-version }}
        components: cargo, clippy, rustfmt
        rustflags: ""
        cache: false # Disable built-in caching since we're using Blacksmith

    - name: Setup Blacksmith Rust Cache
      if: ${{ inputs.extra-cache == 'true' }}
      uses: useblacksmith/rust-cache@v3
      with:
        # Automatically handles:
        # - ~/.cargo/bin
        # - ~/.cargo/registry
        # - ~/.cargo/git
        # - target/ directories
        # - Cargo.lock-based cache invalidation
        shared-key: ${{ inputs.cache-key }}

    - name: Install dependencies
      shell: bash
      run: |
        # Add LLVM 19 repository
        wget -qO- https://apt.llvm.org/llvm-snapshot.gpg.key | sudo tee /etc/apt/trusted.gpg.d/apt.llvm.org.asc
        sudo add-apt-repository -y "deb http://apt.llvm.org/jammy/ llvm-toolchain-jammy-19 main"

        # Update and install dependencies including LLVM 19
        sudo apt-get update -y && sudo apt-get install -y \
          clang-19 llvm-19 llvm-19-dev llvm-19-runtime \
          libmlir-19-dev mlir-19-tools \
          libpolly-19-dev \
          liblld-19-dev \
          libc6-dev libstdc++-11-dev gcc-11 g++-11 \
          libudev-dev protobuf-compiler build-essential \
          libssl-dev pkg-config curl wget git libgmp3-dev netcat-openbsd

        # Set LLVM environment variables for Cairo Native
        echo "MLIR_SYS_190_PREFIX=/usr/lib/llvm-19" >> $GITHUB_ENV
        echo "LLVM_SYS_191_PREFIX=/usr/lib/llvm-19" >> $GITHUB_ENV
        echo "TABLEGEN_190_PREFIX=/usr/lib/llvm-19" >> $GITHUB_ENV

        # Configure linker search paths for Cairo Native runtime compilation
        echo "LIBRARY_PATH=/usr/lib/x86_64-linux-gnu:/usr/lib:/lib/x86_64-linux-gnu:/lib" >> $GITHUB_ENV
        echo "LD_LIBRARY_PATH=/usr/lib/x86_64-linux-gnu:/usr/lib:/lib/x86_64-linux-gnu:/lib" >> $GITHUB_ENV

        # Set up clang-19 as default clang for Cairo Native
        sudo update-alternatives --install /usr/bin/clang clang /usr/lib/llvm-19/bin/clang-19 100
        sudo update-alternatives --install /usr/bin/clang++ clang++ /usr/lib/llvm-19/bin/clang++-19 100

        # Add LLVM 19 binaries to PATH
        echo "/usr/lib/llvm-19/bin" >> $GITHUB_PATH

    - name: Setup mold
      uses: rui314/setup-mold@v1
      with:
        make-default: true
