# yaml-language-server: $schema=https://raw.githubusercontent.com/SchemaStore/schemastore/refs/heads/master/src/schemas/json/github-action.json
name: Action - Setup Rust
description: Sets up the Rust environment with a configurable toolchain

inputs:
  rust-version:
    description: Rust version to set up
    required: true
  extra-cache:
    description: "Whether or not to enable cached dependencies"
    required: false
    default: "true"
  cache-location:
    description: "Path to cached dependencies"
    required: false
    default: "release"
  cache-key:
    description: "Cache key used to retrieve built data. Usually matches the profile of the build"
    required: false
    default: "cache"

runs:
  using: composite
  steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup Rust toolchain
      uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        toolchain: ${{ inputs.rust-version }}
        components: cargo, clippy, rustfmt
        rustflags: ""
        cache: false # Disable built-in caching since we're using Blacksmith

    - name: Setup Blacksmith Rust Cache
      if: ${{ inputs.extra-cache == 'true' }}
      uses: useblacksmith/rust-cache@v3
      with:
        # Automatically handles:
        # - ~/.cargo/bin
        # - ~/.cargo/registry
        # - ~/.cargo/git
        # - target/ directories
        # - Cargo.lock-based cache invalidation
        shared-key: ${{ inputs.cache-key }}

    - name: Install dependencies
      shell: bash
      run: |
        # Install LLVM 19 using Makefile target
        make install-llvm19 SUDO=sudo CODENAME=jammy

        # Set LLVM environment variables for Cairo Native
        echo "MLIR_SYS_190_PREFIX=/usr/lib/llvm-19" >> $GITHUB_ENV
        echo "LLVM_SYS_191_PREFIX=/usr/lib/llvm-19" >> $GITHUB_ENV
        echo "TABLEGEN_190_PREFIX=/usr/lib/llvm-19" >> $GITHUB_ENV

        # Configure linker search paths for Cairo Native runtime compilation
        echo "LIBRARY_PATH=/usr/lib/x86_64-linux-gnu:/usr/lib:/lib/x86_64-linux-gnu:/lib" >> $GITHUB_ENV
        echo "LD_LIBRARY_PATH=/usr/lib/x86_64-linux-gnu:/usr/lib:/lib/x86_64-linux-gnu:/lib" >> $GITHUB_ENV

        # Set up clang-19 as default clang for Cairo Native
        sudo update-alternatives --install /usr/bin/clang clang /usr/lib/llvm-19/bin/clang-19 100
        sudo update-alternatives --install /usr/bin/clang++ clang++ /usr/lib/llvm-19/bin/clang++ 100

        # Also set explicit compiler environment variables for Cairo Native runtime
        # Note: clang-19 handles both C and C++ compilation
        echo "CC=clang-19" >> $GITHUB_ENV
        echo "CXX=clang-19" >> $GITHUB_ENV

        # Configure linker for clang - use lld-19 for Cairo Native runtime compilation
        # These flags are passed to clang when it invokes the linker
        echo "LDFLAGS=-fuse-ld=lld-19" >> $GITHUB_ENV

        # Add LLVM 19 binaries to PATH
        echo "/usr/lib/llvm-19/bin" >> $GITHUB_PATH

    - name: Setup mold
      shell: bash
      run: |
        # Install mold linker with retry logic
        MOLD_VERSION="2.40.4"
        ARCH=$(uname -m)
        MOLD_URL="https://github.com/rui314/mold/releases/download/v${MOLD_VERSION}/mold-${MOLD_VERSION}-${ARCH}-linux.tar.gz"

        echo "Installing mold linker version ${MOLD_VERSION}..."

        # Try up to 5 times with exponential backoff
        for i in 1 2 3 4 5; do
          echo "Attempt $i: Downloading mold from ${MOLD_URL}"

          if wget --retry-connrefused --waitretry=5 --read-timeout=20 --timeout=15 -t 5 \
                  -O /tmp/mold.tar.gz "${MOLD_URL}"; then
            echo "Download successful, extracting..."
            sudo tar -C /usr/local --strip-components=1 --no-overwrite-dir -xzf /tmp/mold.tar.gz
            rm /tmp/mold.tar.gz
            echo "Mold installed successfully"

            # Verify installation
            if command -v mold &> /dev/null; then
              mold --version
              exit 0
            else
              echo "Warning: mold binary not found after installation"
              exit 1
            fi
          else
            echo "Attempt $i failed"
            if [ $i -lt 5 ]; then
              SLEEP_TIME=$((i * 10))
              echo "Retrying in ${SLEEP_TIME} seconds..."
              sleep ${SLEEP_TIME}
            else
              echo "ERROR: Failed to download mold after 5 attempts"
              exit 1
            fi
          fi
        done
