current_version: 7
versions:
  - version: 7
    pr: 789
  - version: 6
    pr: 777
  - version: 5
    pr: 686
  - version: 4
    pr: 714
  - version: 2
    pr: 678
  - version: 1
    pr: 684
  - version: 0
    pr: 647
