current_version: 8
versions:
  - version: 7
    pr: 772
  - version: 6
    pr: 668
  - version: 5
    pr: 678
  - version: 4
    pr: 692
  - version: 3
    pr: 473
  - version: 2
    pr: 495
  - version: 1
    pr: 450
  - version: 0
    pr: 372
