# =============================================================================
# Madara Database Version Configuration
# =============================================================================
#
# This file tracks database schema versions and is used by the build system
# to inject version constants into the binary.
#
# IMPORTANT: When making breaking database changes:
# 1. Increment current_version
# 2. Add a migration in madara/crates/client/db/src/migration/revisions/
# 3. Register the migration in migration/registry.rs
# 4. Add an entry below with version, pr, and description
#
# For more details, see: madara/crates/client/db/src/migration/MIGRATION.md
#
# =============================================================================

# Current database schema version.
# This is the version that new databases will be created with,
# and the version that existing databases will be migrated to.
current_version: 9

# Minimum version that can be migrated from.
# Databases older than this must be deleted and re-synced from scratch.
# When adding migrations, ensure there's a migration path from base_version.
base_version: 8

# Version history (newest first)
# Each entry should have:
#   - version: The schema version number
#   - pr: The PR number that introduced this version
#   - description: (optional) Brief description of changes
versions:
  - version: 9
    description: "SierraClassInfo format migration for SNIP-34 support"
  - version: 8
    pr: 790
    description: "Current schema with migration support"
  - version: 7
    pr: 772
  - version: 6
    pr: 668
  - version: 5
    pr: 678
  - version: 4
    pr: 692
  - version: 3
    pr: 473
  - version: 2
    pr: 495
  - version: 1
    pr: 450
  - version: 0
    pr: 372
    description: "Initial schema"
