// @generated by paradex_codegen
// Contract: AssetsManager

use crate::storage::{storage_key_for_map2_poseidon, storage_key_for_map_poseidon, storage_key_for_variable};
use crate::types::StorageKey;
use once_cell::sync::Lazy;
use starknet_types_core::felt::Felt;

pub static ACCESSCONTROL_BASE: Lazy<StorageKey> = Lazy::new(|| storage_key_for_variable("accesscontrol"));

pub static SRC5_BASE: Lazy<StorageKey> = Lazy::new(|| storage_key_for_variable("src5"));

pub static UPGRADEABLE_BASE: Lazy<StorageKey> = Lazy::new(|| storage_key_for_variable("upgradeable"));

pub static NONCES_BASE: Lazy<StorageKey> = Lazy::new(|| storage_key_for_variable("nonces"));

pub static TOKEN_BASE: Lazy<StorageKey> = Lazy::new(|| storage_key_for_variable("token"));

pub static FUTURE_BASE: Lazy<StorageKey> = Lazy::new(|| storage_key_for_variable("future"));

pub static OPTION_BASE: Lazy<StorageKey> = Lazy::new(|| storage_key_for_variable("option"));

pub static SPOT_BASE: Lazy<StorageKey> = Lazy::new(|| storage_key_for_variable("spot"));
