// @generated by paradex_codegen
// Contract: AssetsManager

use crate::types::ContractAddress;
use starknet_types_core::felt::Felt;

#[derive(Clone, Debug, PartialEq)]
pub struct NamedToken {
    pub token_address: ContractAddress,
    pub token_name: Felt,
}

#[derive(Clone, Debug, PartialEq)]
pub struct SpotAsset {
    pub market: Felt,
    pub base_token_address: ContractAddress,
    pub base_token_name: Felt,
    pub quote_asset: Felt,
}

#[derive(Clone, Debug, PartialEq)]
pub struct TokenAsset {
    pub initial_weight: Felt,
    pub maintenance_weight: Felt,
    pub conversion_weight: Felt,
    pub tick_size: Felt,
    pub token_address: ContractAddress,
    pub token_name: Felt,
}

#[derive(Clone, Debug, PartialEq)]
pub struct PerpetualMarginParams {
    pub imf_base: Felt,
    pub imf_factor: Felt,
    pub mmf_factor: Felt,
    pub imf_shift: Felt,
}

#[derive(Clone, Debug, PartialEq)]
pub struct PerpetualAsset {
    pub market: Felt,
    pub base_asset: Felt,
    pub quote_asset: Felt,
    pub tick_size: Felt,
    pub margin_params: PerpetualMarginParams,
}

#[derive(Clone, Debug, PartialEq)]
pub struct MarketFeeConfigRequest {
    pub maker_api: Felt,
    pub taker_api: Felt,
    pub maker_rpi: Felt,
    pub taker_rpi: Felt,
    pub maker_interactive: Felt,
    pub taker_interactive: Felt,
}

#[derive(Clone, Debug, PartialEq)]
pub struct PerpetualOptionAsset {
    pub market: Felt,
    pub base_asset: Felt,
    pub quote_asset: Felt,
    pub tick_size: Felt,
    pub option_type: Felt,
    pub strike: Felt,
}

#[derive(Clone, Debug, PartialEq)]
pub struct PerpetualOptionMarginParams {
    pub premium_multiplier: Felt,
    pub long_itm: Felt,
    pub short_itm: Felt,
    pub short_otm: Felt,
    pub short_put_cap: Felt,
}

#[derive(Clone, Debug, PartialEq)]
pub struct PerpetualOptionCrossMarginParams {
    pub imf: PerpetualOptionMarginParams,
    pub mmf: PerpetualOptionMarginParams,
}
