// @generated by paradex_codegen
// Contract: assets_future_component

use crate::storage::{storage_key_for_map2_poseidon, storage_key_for_map_poseidon, storage_key_for_variable};
use crate::types::StorageKey;
use once_cell::sync::Lazy;
use starknet_types_core::felt::Felt;

pub static PERPETUAL_FUTURE_ASSET_BASE: Lazy<StorageKey> =
    Lazy::new(|| storage_key_for_variable("perpetual_future_asset"));
pub fn perpetual_future_asset_key(k: Felt) -> StorageKey {
    storage_key_for_map_poseidon("perpetual_future_asset", k)
}

pub static PERPETUAL_FUTURE_ASSET_MIN_SIZE_INCREMENT_BASE: Lazy<StorageKey> =
    Lazy::new(|| storage_key_for_variable("perpetual_future_asset_min_size_increment"));
pub fn perpetual_future_asset_min_size_increment_key(k: Felt) -> StorageKey {
    storage_key_for_map_poseidon("perpetual_future_asset_min_size_increment", k)
}

pub static PERPETUAL_FUTURE_MMF_FACTOR_BASE: Lazy<StorageKey> =
    Lazy::new(|| storage_key_for_variable("perpetual_future_mmf_factor"));

pub static PERPETUAL_FUTURE_MARKET_FEE_CONFIG_V2_BASE: Lazy<StorageKey> =
    Lazy::new(|| storage_key_for_variable("perpetual_future_market_fee_config_v2"));
pub fn perpetual_future_market_fee_config_v2_key(k: Felt) -> StorageKey {
    storage_key_for_map_poseidon("perpetual_future_market_fee_config_v2", k)
}

pub static PERPETUAL_FUTURE_MAX_FEE_RATE_BASE: Lazy<StorageKey> =
    Lazy::new(|| storage_key_for_variable("perpetual_future_max_fee_rate"));
pub fn perpetual_future_max_fee_rate_key(k: Felt) -> StorageKey {
    storage_key_for_map_poseidon("perpetual_future_max_fee_rate", k)
}
