// @generated by paradex_codegen
// Contract: assets_token_component

use crate::storage::{storage_key_for_map2_poseidon, storage_key_for_map_poseidon, storage_key_for_variable};
use crate::types::StorageKey;
use once_cell::sync::Lazy;
use starknet_types_core::felt::Felt;

pub static TOKEN_ASSET_BASE: Lazy<StorageKey> = Lazy::new(|| storage_key_for_variable("token_asset"));
pub fn token_asset_key(k: Felt) -> StorageKey {
    storage_key_for_map_poseidon("token_asset", k)
}
