// @generated by paradex_codegen
// Contract: ParaclearOracle

use crate::types::ContractAddress;
use starknet_types_core::felt::Felt;

#[derive(Clone, Debug, PartialEq)]
pub struct TickData {
    pub asset_key: Felt,
    pub asset_value: Felt,
    pub decimals: Felt,
    pub last_updated_timestamp: Felt,
}
