// @generated by paradex_codegen
// Contract: perpetual_option_component

use crate::storage::{storage_key_for_map2_poseidon, storage_key_for_map_poseidon, storage_key_for_variable};
use crate::types::StorageKey;
use once_cell::sync::Lazy;
use starknet_types_core::felt::Felt;

pub static PERPETUAL_OPTION_ASSET_BASE: Lazy<StorageKey> =
    Lazy::new(|| storage_key_for_variable("perpetual_option_asset"));
pub fn perpetual_option_asset_key(k: Felt) -> StorageKey {
    storage_key_for_map_poseidon("perpetual_option_asset", k)
}

pub static PERPETUAL_OPTION_MARGIN_PARAMS_BASE: Lazy<StorageKey> =
    Lazy::new(|| storage_key_for_variable("perpetual_option_margin_params"));
pub fn perpetual_option_margin_params_key(k: Felt) -> StorageKey {
    storage_key_for_map_poseidon("perpetual_option_margin_params", k)
}

pub static PERPETUAL_OPTIONS_NEGATIVE_FEE_CAP_BASE: Lazy<StorageKey> =
    Lazy::new(|| storage_key_for_variable("perpetual_options_negative_fee_cap"));

pub static PERPETUAL_OPTIONS_POSITIVE_FEE_CAP_BASE: Lazy<StorageKey> =
    Lazy::new(|| storage_key_for_variable("perpetual_options_positive_fee_cap"));
