// @generated by paradex_codegen
// Contract: token_component

use crate::storage::{
    storage_key_for_map, storage_key_for_map2_poseidon, storage_key_for_map_poseidon, storage_key_for_variable,
};
use crate::types::StorageKey;
use once_cell::sync::Lazy;
use starknet_types_core::felt::Felt;

pub static PARACLEAR_WITHDRAWALS_PAUSED_BASE: Lazy<StorageKey> =
    Lazy::new(|| storage_key_for_variable("Paraclear_withdrawals_paused"));

pub static PARACLEAR_DEPOSITS_PAUSED_BASE: Lazy<StorageKey> =
    Lazy::new(|| storage_key_for_variable("Paraclear_deposits_paused"));

pub static PARACLEAR_TOKEN_ASSET_BASE: Lazy<StorageKey> =
    Lazy::new(|| storage_key_for_variable("Paraclear_token_asset"));
pub fn Paraclear_token_asset_key(k: Felt) -> StorageKey {
    storage_key_for_map("Paraclear_token_asset", k)
}

pub static PARACLEAR_TOKEN_ASSET_BALANCE_TAIL_BASE: Lazy<StorageKey> =
    Lazy::new(|| storage_key_for_variable("Paraclear_token_asset_balance_tail"));
pub fn Paraclear_token_asset_balance_tail_key(k: Felt) -> StorageKey {
    storage_key_for_map_poseidon("Paraclear_token_asset_balance_tail", k)
}

pub static PARACLEAR_TOKEN_ASSET_BALANCE_BASE: Lazy<StorageKey> =
    Lazy::new(|| storage_key_for_variable("Paraclear_token_asset_balance"));
pub fn Paraclear_token_asset_balance_key2(k1: Felt, k2: Felt) -> StorageKey {
    storage_key_for_map2_poseidon("Paraclear_token_asset_balance", k1, k2)
}

pub static PARACLEAR_TRANSFER_REGISTRY_BASE: Lazy<StorageKey> =
    Lazy::new(|| storage_key_for_variable("Paraclear_transfer_registry"));
