server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  # Scrape Docker container logs
  - job_name: containerlogs
    static_configs:
      - targets:
          - localhost
        labels:
          job: containerlogs
          __path__: /var/lib/docker/containers/*/*log

    pipeline_stages:
      - json:
          expressions:
            output: log
            stream: stream
            time: time
            tag: attrs.tag
            docker:
      - json:
          expressions:
            name: attrs.name
          source: tag
      - regex:
          expression: ^/(?P<container_name>[\w-]+)$
          source: name
      - labels:
          stream:
          container_name:

  # Scrape orchestrator log file if it exists
  - job_name: orchestrator
    static_configs:
      - targets:
          - localhost
        labels:
          job: orchestrator
          app: madara-orchestrator
          __path__: /logs/orchestrator.log

    pipeline_stages:
      - multiline:
          firstline: '^\d{4}-\d{2}-\d{2}'
      - regex:
          expression: '^(?P<timestamp>[\d-]+T[\d:.]+[\d\w]*)\s+(?P<level>\w+)\s+(?P<message>.*)'
      - labels:
          level:
      - timestamp:
          source: timestamp
          format: RFC3339
