chain_name: "Madara"
# 0.14.2 preset values below are aligned with StarkWare sequencer tag APOLLO-0.14.2-RC.4.
config_version: 2
chain_id: "MADARA_DEVNET"
feeder_gateway_url: "http://localhost:8080/feeder_gateway/"
gateway_url: "http://localhost:8080/gateway/"
native_fee_token_address: "0x04718f5a0fc34cc1af16a1cdee98ffb20c31f5cd61d6ab07201858f4287c938d"
parent_fee_token_address: "0x049d36570d4e46f48e99674bd3fcc84644ddd6b96f7c741b1562b82f9e004dc7"
latest_protocol_version: "0.14.2"
block_time: "10s"
pending_block_update_time: "2s"
execution_batch_size: 16
l1_da_mode: "CALLDATA"
bouncer_config:
  block_max_capacity:
    sierra_gas: 5000000000
    message_segment_length: 3700
    n_events: 5000
    state_diff_size: 4000
    l1_gas: 2500000
    n_txs: 600
    proving_gas: 5000000000
    receipt_l2_gas: 5800000000
  builtin_weights:
    gas_costs:
      pedersen: 3000
      range_check: 90
      ecdsa: 2000000
      ecop: 857850
      bitwise: 583
      keccak: 600000
      poseidon: 10000
      add_mod: 2000
      mul_mod: 2000
      range_check96: 179
      blake: 3334
sequencer_address: "0x123"
eth_core_contract_address: "0x94099942864ea81ccf197e9d71ac53310b1468d8"
eth_gps_statement_verifier: "0xf294781D719D2F4169cE54469C28908E6FA752C1"
mempool_max_transactions: 10000
mempool_max_declare_transactions: 20
mempool_ttl: null
l2_gas_price:
  type: fixed
  price: 25000
