server:
  http_listen_port: 0
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://localhost:3100/loki/api/v1/push

scrape_configs:
  - job_name: orchestrator
    pipeline_stages:
      - json:
          expressions:
            timestamp: timestamp
            level: level
            message: message
            job_id: job_id
            queue: queue
            job_type: job_type
            trace_id: trace_id
            span_type: span_type
            worker: worker
            trigger_id: trigger_id
      - labels:
          level:
          job_id:
          queue:
          job_type:
          span_type:
      - timestamp:
          source: timestamp
          format: RFC3339
    static_configs:
      - targets:
          - localhost
        labels:
          job: orchestrator
          __path__: /dev/stdin