[package]
description = "Madara primitive for starknet blocks"
name = "mp-transactions"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true
homepage.workspace = true

[lints]
workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]

# Madara
mp-chain-config = { workspace = true }
mp-class = { workspace = true }
mp-convert = { workspace = true }

# Starknet
blockifier = { workspace = true }
cairo-lang-starknet-classes = { workspace = true }
cairo-lang-utils = { workspace = true }
cairo-vm = { workspace = true }
starknet-core = { workspace = true }
starknet-types-core = { workspace = true }
starknet-types-rpc = { workspace = true }
starknet_api = { workspace = true }

# Other
anyhow = { workspace = true }
base64 = { workspace = true }
num-bigint = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_with = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }


[dev-dependencies]
assert_matches = { workspace = true }
serde_json = { workspace = true }
