[package]
name = "m-proc-macros"
description = "Madara procedural macros"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true
homepage.workspace = true

[lints]
workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
indoc.workspace = true
proc-macro2.workspace = true
quote.workspace = true
syn.workspace = true

# This is currently only used inside code blocks in doc comments
[dev-dependencies]
jsonrpsee = { workspace = true, default-features = true, features = [
  "macros",
  "server",
] }

[lib]
proc-macro = true
