global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: "madara-orchestrator"
    environment: "production"

scrape_configs:
  # Direct container scraping
  - job_name: "orchestrator-containers"
    static_configs:
      - targets:
          - "orchestrator-1:9090"
          - "orchestrator-2:9090"
          - "orchestrator-3:9090"
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        regex: "([^:]+):.*"
        replacement: "${1}"
      - source_labels: [__address__]
        target_label: container_name
        regex: "([^:]+):.*"
        replacement: "${1}"

  # Health check monitoring for each container
  - job_name: "orchestrator-health"
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
          - "http://orchestrator-1:8080/health"
          - "http://orchestrator-2:8080/health"
          - "http://orchestrator-3:8080/health"
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115
      - source_labels: [__param_target]
        regex: "http://([^:]+):.*"
        target_label: container_name
        replacement: "${1}"

  # Docker container metrics (requires cAdvisor)
  - job_name: "cadvisor"
    static_configs:
      - targets: ["cadvisor:8080"]
    metric_relabel_configs:
      - source_labels: [container_label_com_docker_compose_service]
        target_label: service_name
      - source_labels: [container_label_orchestrator_instance]
        target_label: orchestrator_instance

  # Node exporter for host metrics
  - job_name: "node-exporter"
    static_configs:
      - targets: ["node-exporter:9100"]

# Alerting rules
rule_files:
  - "/etc/prometheus/alerts/*.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets: ["alertmanager:9093"]
