{
 "title": "Madara Orchestrator",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "meter_service",
    "query": "madara_orchestrator_meter_service"
   }
  ]
 },
 "panels": [
  {
   "title": "Snos - latest block completed per job",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "block_state{operation_type=\"create_job\", operation_job_type=\"SnosRun\", job=\"$meter_service\"}",
     "legendFormat": "{{operation_type}}"
    },
    {
     "expr": "block_state{operation_type=\"process_job\", operation_job_type=\"SnosRun\", job=\"$meter_service\"}",
     "legendFormat": "{{operation_type}}"
    },
    {
     "expr": "block_state{operation_type=\"verify_job\", operation_job_type=\"SnosRun\", job=\"$meter_service\", operation_verification_status=\"Verified\"}",
     "legendFormat": "{{operation_type}}"
    }
   ]
  },
  {
   "title": "ProofCreation - latest block completed per job",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "block_state{operation_type=\"create_job\", operation_job_type=\"ProofCreation\", job=\"$meter_service\"}",
     "legendFormat": "{{operation_type}}"
    },
    {
     "expr": "block_state{operation_type=\"process_job\", operation_job_type=\"ProofCreation\", job=\"$meter_service\"}",
     "legendFormat": "{{operation_type}}"
    },
    {
     "expr": "block_state{operation_type=\"verify_job\", operation_job_type=\"ProofCreation\", job=\"$meter_service\", operation_verification_status=\"Verified\"}",
     "legendFormat": "{{operation_type}}"
    }
   ]
  },
  {
   "title": "DataSubmission - latest block completed per job",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "block_state{operation_type=\"create_job\", operation_job_type=\"DataSubmission\", job=\"$meter_service\"}",
     "legendFormat": "{{operation_type}}"
    },
    {
     "expr": "block_state{operation_type=\"process_job\", operation_job_type=\"DataSubmission\", job=\"$meter_service\"}",
     "legendFormat": "{{operation_type}}"
    },
    {
     "expr": "block_state{operation_type=\"verify_job\", operation_job_type=\"DataSubmission\", job=\"$meter_service\", operation_verification_status=\"Verified\"}",
     "legendFormat": "{{operation_type}}"
    }
   ]
  },
  {
   "title": "StateTransition - latest block completed per job",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "block_state{operation_type=\"create_job\", operation_job_type=\"StateTransition\", job=\"$meter_service\"}",
     "legendFormat": "{{operation_type}}"
    },
    {
     "expr": "block_state{operation_type=\"process_job\", operation_job_type=\"StateTransition\", job=\"$meter_service\"}",
     "legendFormat": "{{operation_type}}"
    },
    {
     "expr": "block_state{operation_type=\"verify_job\", operation_job_type=\"StateTransition\", job=\"$meter_service\", operation_verification_status=\"Verified\"}",
     "legendFormat": "{{operation_type}}"
    }
   ]
  },
  {
   "title": "Successful Create Jobs over time (since last start)",
   "type": "timeseries",
   "description": "grouped by job_type",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "successful_job_operations_jobs_total{operation_type=\"create_job\", job=\"$meter_service\", operation_job_type=\"DataSubmission\"}",
     "legendFormat": "{{operation_job_type}}"
    },
    {
     "expr": "successful_job_operations_jobs_total{operation_type=\"create_job\", job=\"$meter_service\", operation_job_type=\"SnosRun\"}",
     "legendFormat": "{{operation_job_type}}"
    },
    {
     "expr": "successful_job_operations_jobs_total{operation_type=\"create_job\", job=\"$meter_service\", operation_job_type=\"ProofCreation\"}",
     "legendFormat": "{{operation_job_type}}"
    },
    {
     "expr": "successful_job_operations_jobs_total{operation_type=\"create_job\", job=\"$meter_service\", operation_job_type=\"StateTransition\"}",
     "legendFormat": "{{operation_job_type}}"
    }
   ]
  },
  {
   "title": "Failed Create Jobs over time",
   "type": "timeseries",
   "description": "grouped by job_type",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "failed_job_operations_jobs_total{operation_type=\"create_job\", job=\"$meter_service\", operation_job_type=\"SnosRun\" }",
     "legendFormat": "{{operation_job_type}}"
    },
    {
     "expr": "failed_job_operations_jobs_total{operation_type=\"create_job\", job=\"$meter_service\", operation_job_type=\"ProofCreation\" }",
     "legendFormat": "{{operation_job_type}}"
    },
    {
     "expr": "failed_job_operations_jobs_total{operation_type=\"create_job\", job=\"$meter_service\", operation_job_type=\"DataSubmission\" }",
     "legendFormat": "{{operation_job_type}}"
    },
    {
     "expr": "failed_job_operations_jobs_total{operation_type=\"create_job\", job=\"$meter_service\", operation_job_type=\"StateTransition\" }",
     "legendFormat": "{{operation_job_type}}"
    }
   ]
  },
  {
   "title": "Successful Process Jobs over time (since last start)",
   "type": "timeseries",
   "description": "grouped by job_type",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "(successful_job_operations_jobs_total{operation_type=\"process_job\", job=\"$meter_service\", operation_job_type=\"SnosRun\"})",
     "legendFormat": "{{operation_job_type}}"
    },
    {
     "expr": "(successful_job_operations_jobs_total{operation_type=\"process_job\", job=\"$meter_service\", operation_job_type=\"ProofCreation\"})",
     "legendFormat": "{{operation_job_type}}"
    },
    {
     "expr": "(successful_job_operations_jobs_total{operation_type=\"process_job\", job=\"$meter_service\", operation_job_type=\"DataSubmission\"})",
     "legendFormat": "{{operation_job_type}}"
    },
    {
     "expr": "(successful_job_operations_jobs_total{operation_type=\"process_job\", job=\"$meter_service\", operation_job_type=\"StateTransition\"})",
     "legendFormat": "{{operation_job_type}}"
    }
   ]
  },
  {
   "title": "Failed Process Jobs over time",
   "type": "timeseries",
   "description": "grouped by job_type",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "failed_job_operations_jobs_total{operation_type=\"process_job\", job=\"$meter_service\", operation_job_type=\"SnosRun\" }",
     "legendFormat": "{{operation_job_type}}"
    },
    {
     "expr": "failed_job_operations_jobs_total{operation_type=\"process_job\", job=\"$meter_service\", operation_job_type=\"ProofCreation\" }",
     "legendFormat": "{{operation_job_type}}"
    },
    {
     "expr": "failed_job_operations_jobs_total{operation_type=\"process_job\", job=\"$meter_service\", operation_job_type=\"DataSubmission\" }",
     "legendFormat": "{{operation_job_type}}"
    },
    {
     "expr": "failed_job_operations_jobs_total{operation_type=\"process_job\", job=\"$meter_service\", operation_job_type=\"StateTransition\" }",
     "legendFormat": "{{operation_job_type}}"
    }
   ]
  },
  {
   "title": "Successful Verify Jobs over time (since last start)",
   "type": "timeseries",
   "description": "grouped by job_type",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "successful_job_operations_jobs_total{operation_type=\"verify_job\", job=\"$meter_service\", operation_job_type=\"SnosRun\", operation_verification_status=\"Verified\"}",
     "legendFormat": "{{operation_job_type}}"
    },
    {
     "expr": "successful_job_operations_jobs_total{operation_type=\"verify_job\", job=\"$meter_service\", operation_job_type=\"ProofCreation\", operation_verification_status=\"Verified\"}",
     "legendFormat": "{{operation_job_type}}"
    },
    {
     "expr": "successful_job_operations_jobs_total{operation_type=\"verify_job\", job=\"$meter_service\", operation_job_type=\"DataSubmission\", operation_verification_status=\"Verified\"}",
     "legendFormat": "{{operation_job_type}}"
    },
    {
     "expr": "successful_job_operations_jobs_total{operation_type=\"verify_job\", job=\"$meter_service\", operation_job_type=\"StateTransition\", operation_verification_status=\"Verified\"}",
     "legendFormat": "{{operation_job_type}}"
    }
   ]
  },
  {
   "title": "Failed Verify Jobs over time",
   "type": "timeseries",
   "description": "grouped by job_type",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "expr": "failed_job_operations_jobs_total{operation_type=\"verify_job\", job=\"$meter_service\", operation_job_type=\"SnosRun\", operation_verification_status=\"Rejected\"}",
     "legendFormat": "{{operation_job_type}}"
    },
    {
     "expr": "failed_job_operations_jobs_total{operation_type=\"verify_job\", job=\"$meter_service\", operation_job_type=\"ProofCreation\", operation_verification_status=\"Rejected\"}",
     "legendFormat": "{{operation_job_type}}"
    },
    {
     "expr": "failed_job_operations_jobs_total{operation_type=\"verify_job\", job=\"$meter_service\", operation_job_type=\"DataSubmission\", operation_verification_status=\"Rejected\"}",
     "legendFormat": "{{operation_job_type}}"
    },
    {
     "expr": "failed_job_operations_jobs_total{operation_type=\"verify_job\", job=\"$meter_service\", operation_job_type=\"StateTransition\", operation_verification_status=\"Rejected\"}",
     "legendFormat": "{{operation_job_type}}"
    }
   ]
  },
  {
   "title": "Create Job response time over time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "jobs_response_time_seconds{job=\"$meter_service\", operation_type=\"create_job\"}",
     "legendFormat": "{{operation_job_type}}"
    }
   ]
  },
  {
   "title": "Process Job response time over time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "jobs_response_time_seconds{job=\"$meter_service\", operation_type=\"process_job\"}",
     "legendFormat": "{{operation_job_type}}"
    }
   ]
  },
  {
   "title": "Verify Job response time over time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "jobs_response_time_seconds{job=\"$meter_service\", operation_type=\"verify_job\", operation_verification_status=\"Verified\"}",
     "legendFormat": "{{operation_job_type}}"
    }
   ]
  },
  {
   "title": "Response time of DB queries (per method)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "quantile(0.99, db_calls_response_time_seconds{job=\"$meter_service\", db_operation_name=\"update_job\"})",
     "legendFormat": "update_job"
    },
    {
     "expr": "quantile(0.99, db_calls_response_time_seconds{job=\"$meter_service\", db_operation_name=\"create_job\"})",
     "legendFormat": "create_job"
    },
    {
     "expr": "quantile(0.99, db_calls_response_time_seconds{job=\"$meter_service\", db_operation_name=\"get_job_by_id\"})",
     "legendFormat": "get_job_by_id"
    },
    {
     "expr": "quantile(0.99, db_calls_response_time_seconds{job=\"$meter_service\", db_operation_name=\"get_job_by_internal_id_and_type\"})",
     "legendFormat": "get_job_by_internal_id_and_type"
    },
    {
     "expr": "quantile(0.99, db_calls_response_time_seconds{job=\"$meter_service\", db_operation_name=\"get_latest_job_by_type\"})",
     "legendFormat": "get_latest_job_by_type"
    },
    {
     "expr": "quantile(0.99, db_calls_response_time_seconds{job=\"$meter_service\", db_operation_name=\"get_jobs_without_successor\"})",
     "legendFormat": "get_jobs_without_successor"
    },
    {
     "expr": "quantile(0.99, db_calls_response_time_seconds{job=\"$meter_service\", db_operation_name=\"get_latest_job_by_type_and_status\"})",
     "legendFormat": "get_latest_job_by_type_and_status"
    },
    {
     "expr": "quantile(0.99, db_calls_response_time_seconds{job=\"$meter_service\", db_operation_name=\"get_jobs_after_internal_id_by_job_type\"})",
     "legendFormat": "get_jobs_after_internal_id_by_job_type"
    },
    {
     "expr": "quantile(0.99, db_calls_response_time_seconds{job=\"$meter_service\", db_operation_name=\"get_jobs_by_statuses\"})",
     "legendFormat": "get_jobs_by_statuses"
    }
   ]
  },
  {
   "title": "Verification time for Proof Creation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "verification_time_milliseconds{operation_job_type=\"ProofCreation\", job=\"$meter_service\"}",
     "legendFormat": "{{operation_job_type}}"
    }
   ]
  },
  {
   "title": "Failed Jobs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "targets": [
    {
     "expr": "failed_jobs_total{job=\"$meter_service\"}",
     "legendFormat": "{{operation_job_type}}"
    },
    {
     "expr": "successful_job_operations_jobs_total{operation_type=\"verify_job\", job=\"$meter_service\", operation_job_status=\"VerificationTimeout\"}",
     "legendFormat": "{{operation_job_type}}"
    }
   ]
  }
 ]
}