name: "Rust Environment Setup"
description: "Sets up the Rust environment with configurable toolchain, cache, and dependencies"

inputs:
  rust-version:
    description: "Rust toolchain version to use"
    required: true
  cache-key:
    description: "Custom cache key for rust-cache"
    required: false
    default: "cache"
  install-mold:
    description: "Whether to install mold linker"
    required: true
  install-scarb:
    description: "Whether to install Scarb"
    required: true
  scarb-version:
    description: "Scarb version to install"
    required: true
  install-foundry:
    description: "Whether to install Foundry"
    required: false
    default: "false"
  foundry-version:
    description: "Foundry version to install"
    required: false
  python-version:
    description: "Python version to use for Cairo 0/SNOS"
    required: false
  build-snos:
    description: "Whether to build SNOS files"
    required: false
    default: "false"

runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: true

    - uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: clang llvm libudev-dev protobuf-compiler gcc g++ build-essential libssl-dev pkg-config curl wget git libgmp3-dev
        version: 1.0

    - uses: actions/cache@v4
      id: cache-sscache
      with:
        path: |
          ~/.cache/sccache
        key: ${{ runner.os }}-${{ inputs.rust-version }}-${{ inputs.cache-key }}-sccache

    - name: Run sccache-cache
      uses: mozilla-actions/sccache-action@v0.0.8

    - name: Set Rust caching env vars
      if: github.event_name != 'release' && github.event_name != 'workflow_dispatch'
      shell: bash
      run: |
        echo "SCCACHE_GHA_ENABLED=true" >> $GITHUB_ENV
        echo "RUSTC_WRAPPER=sccache" >> $GITHUB_ENV
        sccache --show-stats
        
    - uses: actions/cache@v4
      id: cache-cargo
      with:
        path: |
          ~/.cargo/bin
          ~/.cargo/registry
          ~/.cargo/git
          target/
          cairo/target/
        key: ${{ runner.os }}-${{ inputs.rust-version }}-cargo-${{ hashFiles('**/Cargo.lock') }}

    - name: Setup Rust toolchain
      if: steps.cache-cargo.outputs.cache-hit != 'true'
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: ${{ inputs.rust-version }}
        components: rustfmt, clippy

    - name: Setup Rust cache
      uses: Swatinem/rust-cache@v2
      with:
        shared-key: ${{ inputs.cache-key }}

    - name: Setup mold linker
      if: ${{ inputs.install-mold == 'true' }}
      uses: rui314/setup-mold@v1

    - name: Setup Scarb
      if: ${{ inputs.install-scarb == 'true' }}
      uses: software-mansion/setup-scarb@v1
      with:
        scarb-version: ${{ inputs.scarb-version }}

    - name: Setup Foundry
      if: ${{ inputs.install-foundry == 'true' }}
      uses: foundry-rs/foundry-toolchain@v1
      with:
        version: ${{ inputs.foundry-version }}

    - name: Setup Python for Cairo 0
      if: ${{ inputs.build-snos == 'true' }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python-version }}

    - name: Retrieve SNOS Commit
      id: retrieve-snos-commit
      if: ${{ inputs.build-snos == 'true' }}
      shell: bash
      run: |
        CAIRO_LANG_COMMIT=$(git submodule status orchestrator/cairo-lang | cut -d' ' -f1 | grep -o '[A-z0-9]*')
        echo "SNOS Cache hash: CAIRO_LANG_COMMIT"
        echo "CAIRO_LANG_COMMIT=$CAIRO_LANG_COMMIT" >> $GITHUB_ENV

    - name: Cache SNOS packages
      id: cache-snos
      if: ${{ inputs.build-snos == 'true' }}
      uses: actions/cache@v4
      with:
        path: orchestrator/build
        key: snos-${{ inputs.python-version }}-${{ env.CAIRO_LANG_COMMIT }}

    - name: Cache Python packages
      id: cache-python
      if: ${{ inputs.build-snos == 'true' && steps.cache-snos.outputs.cache-hit != 'true' }}
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: pip-${{ runner.os }}-python-${{ inputs.python-version }}

    - name: Install Cairo 0
      if: ${{ inputs.build-snos == 'true'  && steps.cache-snos.outputs.cache-hit != 'true' && steps.cache-python.outputs.cache-hit != 'true' }}
      shell: bash
      run: |
        # Installing deps
        pip3 install ecdsa fastecdsa sympy

        # Installing cairo lang
        pip3 install cairo-lang

    - name: Build SNOS files
      if: ${{ inputs.build-snos == 'true' && steps.cache-snos.outputs.cache-hit != 'true' }}
      shell: bash
      run: |
        make snos
