chain_name: ""
chain_id: ""
l1_da_mode: ""
feeder_gateway_url: ""
gateway_url: ""
native_fee_token_address: ""
parent_fee_token_address: ""
latest_protocol_version: ""
block_time: ""
pending_block_update_time: ""
execution_batch_size:
l2_gas_target: ""
min_l2_gas_price: ""
l2_gas_price_max_change_denominator: ""
bouncer_config:
  block_max_capacity:
    sierra_gas: ""
    message_segment_length: ""
    n_events: ""
    state_diff_size: ""
    l1_gas: ""
    n_txs: ""
  builtin_weights:
    pedersen: ""
    range_check: ""
    ecdsa: ""
    bitwise: ""
    poseidon: ""
    keccak: ""
    ec_op: ""
    mul_mod: ""
    add_mod: ""
    range_check96: ""
sequencer_address: ""
eth_core_contract_address: ""
eth_gps_statement_verifier: ""
