[package]
description = "Madara primitive for RPC"
name = "mp-rpc"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true
homepage.workspace = true

[lints]
workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[package.metadata.attribution]
includes-code-from = [
  "starknet-types-rpc (MIT) - https://github.com/starknet-io/types-rs",
]

[dependencies]

# Starknet
starknet-types-core = { workspace = true }

# Other
serde = { workspace = true, features = ["derive"] }

[dev-dependencies]
serde_json = { workspace = true }
