# yaml-language-server: $schema=https://raw.githubusercontent.com/SchemaStore/schemastore/refs/heads/master/src/schemas/json/github-action.json
name: Action - Setup Python Cairo
description: Sets up Python virtual environment with cairo0 tools for apollo_starknet_os_program

inputs:
  python-version:
    description: Python version to set up
    required: false
    default: "3.9"

runs:
  using: composite
  steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}

    #    - name: Cache Python dependencies
    #      uses: actions/cache@v4
    #      with:
    #        path: |
    #          sequencer_venv
    #          ~/.cache/pip
    #        key: python-cairo-${{ runner.os }}-${{ inputs.python-version }}-v3
    #        restore-keys: |
    #          python-cairo-${{ runner.os }}-${{ inputs.python-version }}-

    - name: Setup Python virtual environment with cairo-lang
      shell: bash
      run: |
        # Create virtual environment
        python3 -m venv sequencer_venv
        source sequencer_venv/bin/activate

        # Pin cairo-lang to exact version required by build scripts
        # Note: We explicitly pin to 0.14.0.1 instead of using sequencer's requirements.txt
        # because the sequencer may have a newer alpha version that's incompatible with our build
        echo "Installing cairo-lang==0.14.0.1 (exact version required by build scripts)..."
        pip install --upgrade pip
        pip install cairo-lang==0.14.0.1 "numpy<2.0"

        # Verify cairo-compile is available and has the correct version
        if command -v cairo-compile >/dev/null 2>&1; then
          CAIRO_VERSION=$(cairo-compile --version 2>&1 | grep -oE '[0-9]+\.[0-9]+\.[0-9]+(\.[0-9]+)?' || echo "unknown")
          echo "✓ cairo-compile is available at: $(which cairo-compile)"
          echo "✓ cairo-compile version: $CAIRO_VERSION"

          # Verify the version is exactly what we expect
          if [[ "$CAIRO_VERSION" != "0.14.0.1" ]]; then
            echo "⚠️  Warning: cairo-compile version is $CAIRO_VERSION, expected 0.14.0.1"
            echo "This may cause build failures. Please check cairo-lang installation."
          fi
        else
          echo "❌ cairo-compile not found in PATH after installing requirements"
          echo "Installed Python packages:"
          pip list
          exit 1
        fi

        echo "✓ Python virtual environment setup complete with cairo-lang==0.14.0.1"

    - name: Activate virtual environment for subsequent steps
      shell: bash
      run: |
        # Get the absolute path to the virtual environment
        VENV_PATH="$(pwd)/sequencer_venv"

        # Add virtual environment to PATH for subsequent steps
        echo "$VENV_PATH/bin" >> $GITHUB_PATH

        # Set environment variables that indicate we're in a virtual environment
        echo "VIRTUAL_ENV=$VENV_PATH" >> $GITHUB_ENV
        echo "PATH=$VENV_PATH/bin:$PATH" >> $GITHUB_ENV

        # Also set Python-specific environment variables
        echo "PYTHONPATH=$VENV_PATH/lib/python${{ inputs.python-version }}/site-packages" >> $GITHUB_ENV

        # Verify the setup
        echo "✓ Virtual environment activated for subsequent workflow steps"
        echo "VENV_PATH: $VENV_PATH"
        echo "Python executable will be: $VENV_PATH/bin/python"
        echo "Cairo-compile will be: $VENV_PATH/bin/cairo-compile"
