[package]
name = "orchestrator-starknet-settlement-client"
version.workspace = true
edition.workspace = true

[dependencies]
alloy = { workspace = true, features = ["full", "node-bindings"] }
alloy-primitives = { workspace = true, default-features = false }
async-trait = { workspace = true }
c-kzg = { workspace = true }
color-eyre = { workspace = true }
crypto-bigint = { workspace = true }
dotenvy.workspace = true
lazy_static = { workspace = true }
log = { workspace = true }
mockall = { workspace = true }
orchestrator-settlement-client-interface = { workspace = true }
orchestrator-utils = { workspace = true }
reqwest = { workspace = true }
rstest = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
starknet = { workspace = true }
starknet-accounts = { workspace = true }
starknet-core = { workspace = true }
starknet-providers = { workspace = true }
tempfile.workspace = true
tokio = { workspace = true }
url = { workspace = true }

#Instrumentation
hex = { workspace = true }
opentelemetry = { workspace = true, features = ["metrics", "logs"] }
opentelemetry-appender-tracing = { workspace = true, default-features = false }
opentelemetry-otlp = { workspace = true, features = [
  "tonic",
  "metrics",
  "logs",
] }
opentelemetry-semantic-conventions = { workspace = true }
opentelemetry_sdk = { workspace = true, features = ["rt-tokio", "logs"] }
thiserror = { workspace = true }
tracing = { workspace = true }
tracing-core = { workspace = true, default-features = false }
tracing-opentelemetry = { workspace = true }
tracing-subscriber = { workspace = true, features = ["env-filter"] }


[dev-dependencies]
async-std.workspace = true
serde_json.workspace = true
tokio-test = "*"

[build-dependencies]
build-version.workspace = true
