---
# yaml-language-server: $schema=https://raw.githubusercontent.com/SchemaStore/schemastore/refs/heads/master/src/schemas/json/github-workflow.json
name: Task - Build Orchestrator

on:
  workflow_dispatch:
  workflow_call:

jobs:
  check-binaries:
    permissions:
      pull-requests: write
    runs-on: blacksmith-16vcpu-ubuntu-2204

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Load env
        uses: ./.github/actions/load-env

      - name: Rust setup
        uses: ./.github/actions/setup-rust
        with:
          rust-version: ${{ env.BUILD_RUST_VERSION }}
          extra-cache: false

      - name: Compile artifacts
        run: make artifacts

      # Check Orchestrator
      - name: Cargo check
        run: |
          export GIT_COMMIT_HASH=$GITHUB_SHA
          cargo check -p orchestrator --release
