---
# yaml-language-server: $schema=https://raw.githubusercontent.com/SchemaStore/schemastore/refs/heads/master/src/schemas/json/github-workflow.json
name: Task - Run CLI tests
on:
  workflow_dispatch:
    inputs:
      madara-binary-hash:
        description: "Hash used to retrieve the madara binary artifact"
        required: true
        type: string
  workflow_call:
    inputs:
      madara-binary-hash:
        description: "Hash used to retrieve the madara binary artifact"
        required: true
        type: string
jobs:
  test-cli:
    runs-on: blacksmith-4vcpu-ubuntu-2204
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Load env
        uses: ./.github/actions/load-env
      - name: Download Madara binary
        uses: actions/download-artifact@v4
        with:
          name: madara-binary-${{ inputs.madara-binary-hash }}
          path: target/release/
      - name: Make Madara binary executable
        run: chmod +x target/release/madara
      - name: Run cli without arguments
        timeout-minutes: 20
        run: |
          ./target/release/madara --no-l1-sync --devnet &
          MADARA_PID=$!
          while ! curl -s -X POST http://localhost:9944 -H "Content-Type: application/json" -d '{"jsonrpc":"2.0","method":"starknet_chainId","params":[],"id":1}' | grep -q result; do sleep 1; done
          kill $MADARA_PID
          wait $MADARA_PID || true
      - name: Run cli pointing to a file
        timeout-minutes: 20
        run: |
          ./target/release/madara --no-l1-sync --devnet --config-file ./configs/args/config.json &
          MADARA_PID=$!
          while ! curl -s -X POST http://localhost:9944 -H "Content-Type: application/json" -d '{"jsonrpc":"2.0","method":"starknet_chainId","params":[],"id":1}' | grep -q result; do sleep 1; done
          kill $MADARA_PID
          wait $MADARA_PID || true
