---
# yaml-language-server: $schema=https://raw.githubusercontent.com/SchemaStore/schemastore/refs/heads/master/src/schemas/json/github-workflow.json
name: Task - Publish Nightly Release

on:
  workflow_call:
    inputs:
      image-name:
        description: Name of the Docker image
        required: true
        type: string
      tag:
        description: Image tag
        required: true
        type: string
      tag-version:
        description: Image tag (with identifying version information)
        required: true
        type: string
      registry:
        description: Container registry domain
        required: false
        default: ghcr.io
        type: string
      should_run:
        required: false
        default: true
        type: string

permissions:
  contents: read
  packages: write
  attestations: write
  id-token: write

jobs:
  check:
    runs-on: blacksmith-16vcpu-ubuntu-2204
    steps:
      - run: echo "Publishing ${{ inputs.tag-version }}"

  publish-image:
    runs-on: blacksmith-16vcpu-ubuntu-2204
    if: inputs.should_run == 'true'

    steps:
      - name: Download ${{ inputs.image-name }}
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.image-name }}
          path: ${{ runner.temp }}
      - run: docker load --input ${{ runner.temp }}/${{ inputs.image-name }}.tar

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ inputs.registry }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish image
        run: |
          docker push ${{ inputs.tag }}
          docker push ${{ inputs.tag-version }}
